type = "directrequest"
schemaVersion = 1
name = "[DR] (Get > Uint256[array])"
externalJobID = "90ec64e8-3b32-429b-958d-eb238a23eeed"
maxTaskDuration = "0s"
contractAddress = "0x14fB588AD6DA21d7F790D477354DE923AE5BeB07"
minIncomingConfirmations = 0
minContractPaymentLinkJuels = "150000000000000000"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]
    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    fetch        [type="http" method=GET url="$(decode_cbor.get)"]
    parse        [type=jsonparse path="data,results" data="$(fetch)"]
    encode_large [type="ethabiencode"
                abi="(bytes32 requestId, uint256[] _data)"
                data="{\\"requestId\\": $(decode_log.requestId), \\"_data\\": $(parse)}"
                ]
    encode_tx  [type="ethabiencode"
                abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\":   $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_large)}"
                ]
    submit_tx    [type="ethtx" to="0x14fB588AD6DA21d7F790D477354DE923AE5BeB07" data="$(encode_tx)"]
    
    decode_log -> decode_cbor -> fetch -> parse -> encode_large -> encode_tx -> submit_tx
"""
